#!/bin/bash

#Volume increments in percent
INC=5

if [ "$1" == "down" ]
then
 amixer -q set Master $INC%- unmute
 TEXT=$(amixer sget Master | tail -1 | cut -d' ' -f7 | sed 's/\(\[\|\]\)//g')
elif [ "$1" == "up" ]
then
 amixer -q set Master $INC%+ unmute
 TEXT=$(amixer sget Master | tail -1 | cut -d' ' -f7 | sed 's/\(\[\|\]\)//g')
elif [ "$1" == "toggle" ]
then
 amixer -q set Master toggle
 TEXT=$(amixer sget Master | tail -1 | cut -d' ' -f8 | sed 's/\(\[\|\]\)//g')
else
 echo "Usage volume [up | down | toggle]\n"
fi

ID=$(cat $HOME/.i3/.notify_volume)
if [ $ID -z ]
then
    ID=0
fi

$HOME/.i3/scripts/notify.py volume $ID "Volume: $TEXT" "" "" 2000 > $HOME/.i3/.notify_volume
